#!/usr/bin/env python3
"""
Parse nextest JUnit XML output and extract structured test results.

This script parses the JUnit XML file generated by cargo-nextest and extracts
test statistics and failed test information with error messages.
Generic for any Rust project using cargo-nextest.
"""

import argparse
import sys
import xml.etree.ElementTree as ET
from typing import Dict, List, Tuple


def parse_junit_xml(junit_file_path: str) -> Tuple[Dict[str, str], List[Dict[str, str]]]:
    """
    Parse JUnit XML file and extract test results.
    
    Args:
        junit_file_path: Path to the JUnit XML file
    
    Returns:
        Tuple of (statistics dict, failed tests list)
        Statistics dict contains: total_tests, passed, failed, timed_out
        Failed tests list contains dicts with: name, message, details
    """
    try:
        tree = ET.parse(junit_file_path)
        root = tree.getroot()
    except FileNotFoundError:
        print(f"Error: JUnit XML file not found: {junit_file_path}", file=sys.stderr)
        sys.exit(1)
    except ET.ParseError as e:
        print(f"Error: Invalid XML format in {junit_file_path}: {e}", file=sys.stderr)
        sys.exit(1)
    except PermissionError:
        print(f"Error: Permission denied reading {junit_file_path}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: Failed to parse JUnit XML file {junit_file_path}: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Extract statistics from testsuite element
    # JUnit XML format: <testsuite tests="N" failures="M" errors="E" skipped="S">
    testsuite = root.find('.//testsuite')
    if testsuite is None:
        # Try root element if it's the testsuite
        testsuite = root
    
    total_tests = testsuite.get('tests', '0')
    failures = int(testsuite.get('failures', '0'))
    errors = int(testsuite.get('errors', '0'))
    skipped = int(testsuite.get('skipped', '0'))
    
    # Calculate passed (total - failures - errors - skipped)
    total = int(total_tests)
    failed = failures + errors
    passed = total - failed - skipped
    
    statistics = {
        'total_tests': str(total),
        'passed': str(passed),
        'failed': str(failed),
        'timed_out': '0'
    }
    
    # Extract failed test cases with error messages
    failed_tests = []
    
    # Find all testcase elements with failure or error
    for testcase in root.findall('.//testcase'):
        failure = testcase.find('failure')
        error = testcase.find('error')
        
        if failure is not None or error is not None:
            test_name = testcase.get('name', 'unknown')
            classname = testcase.get('classname', '')
            
            # Combine classname and name for full test path
            if classname:
                full_name = f"{classname}::{test_name}"
            else:
                full_name = test_name
            
            # Get failure message and details
            failure_elem = failure if failure is not None else error
            failure_message = failure_elem.get('message', '')
            failure_details = failure_elem.text or ''
            
            # Check if it's a timeout
            is_timeout = 'timeout' in failure_message.lower() or 'timed out' in failure_message.lower()
            if is_timeout:
                statistics['timed_out'] = str(int(statistics['timed_out']) + 1)
            
            failed_tests.append({
                'name': full_name,
                'message': failure_message,
                'details': failure_details.strip(),
                'is_timeout': is_timeout
            })
    
    return statistics, failed_tests


def format_failed_tests_list(failed_tests: List[Dict[str, str]]) -> str:
    """
    Format failed tests as a simple markdown list.
    
    Args:
        failed_tests: List of failed test dicts
    
    Returns:
        Formatted markdown string
    """
    if not failed_tests:
        return ""
    
    lines = []
    for test in failed_tests:
        suffix = " (タイムアウト)" if test['is_timeout'] else ""
        lines.append(f"- {test['name']}{suffix}")
    
    return "\n".join(lines)


def format_failed_tests_with_errors(failed_tests: List[Dict[str, str]]) -> str:
    """
    Format failed tests with error messages in markdown.
    
    Args:
        failed_tests: List of failed test dicts
    
    Returns:
        Formatted markdown string with error messages
    """
    if not failed_tests:
        return ""
    
    lines = []
    for test in failed_tests:
        suffix = " (タイムアウト)" if test['is_timeout'] else ""
        lines.append(f"### {test['name']}{suffix}")
        lines.append("")
        if test['message']:
            lines.append(f"**Error**: {test['message']}")
            lines.append("")
        if test['details']:
            lines.append("```")
            lines.append(test['details'])
            lines.append("```")
            lines.append("")
    
    return "\n".join(lines)


def main():
    """
    Main entry point for the script.
    """
    parser = argparse.ArgumentParser(
        description="Parse nextest JUnit XML output and extract test results."
    )
    
    parser.add_argument(
        "--junit-file",
        required=True,
        help="Path to the JUnit XML file generated by nextest"
    )
    
    parser.add_argument(
        "--output-format",
        choices=["stats", "list", "errors", "all"],
        default="all",
        help="Output format: stats (statistics only), list (simple test list), errors (tests with error messages), all (everything)"
    )
    
    args = parser.parse_args()
    
    statistics, failed_tests = parse_junit_xml(args.junit_file)
    
    if args.output_format in ["stats", "all"]:
        print(f"total_tests={statistics['total_tests']}")
        print(f"passed={statistics['passed']}")
        print(f"failed={statistics['failed']}")
        print(f"timed_out={statistics['timed_out']}")
    
    if args.output_format in ["list", "all"]:
        if args.output_format == "all":
            print("---FAILED_TESTS---")
        print(format_failed_tests_list(failed_tests))
    
    if args.output_format in ["errors", "all"]:
        if args.output_format == "all":
            print("---ERROR_DETAILS---")
        print(format_failed_tests_with_errors(failed_tests))
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
