#!/usr/bin/env python3
"""
Parse nextest JUnit XML output and extract structured test results.

This script parses the JUnit XML file generated by cargo-nextest and extracts
test statistics and categorized failed test information.
"""

import argparse
import sys
import xml.etree.ElementTree as ET
from typing import Dict, List, Tuple


def categorize_test(test_name: str) -> str:
    """
    Categorize a test based on its name.
    
    Args:
        test_name: The full test name (e.g., "module::test_name")
    
    Returns:
        Category name
    """
    lower_name = test_name.lower()
    
    if 'pipe' in lower_name:
        return "Pipe Tests"
    elif 'cli_integration' in lower_name:
        return "CLI Integration Tests"
    elif 'client' in lower_name:
        return "Client Integration Tests"
    elif 'interactive' in lower_name:
        return "Interactive Mode Tests"
    elif 'server' in lower_name:
        return "Server Integration Tests"
    else:
        return "その他"


def parse_junit_xml(junit_file_path: str) -> Tuple[Dict[str, str], Dict[str, List[str]]]:
    """
    Parse JUnit XML file and extract test results.
    
    Args:
        junit_file_path: Path to the JUnit XML file
    
    Returns:
        Tuple of (statistics dict, categorized failed tests dict)
        Statistics dict contains: total_tests, passed, failed, timed_out
        Categorized dict maps category names to lists of failed test names
    """
    try:
        tree = ET.parse(junit_file_path)
        root = tree.getroot()
    except FileNotFoundError:
        print(f"Error: JUnit XML file not found: {junit_file_path}", file=sys.stderr)
        sys.exit(1)
    except ET.ParseError as e:
        print(f"Error: Invalid XML format in {junit_file_path}: {e}", file=sys.stderr)
        sys.exit(1)
    except PermissionError:
        print(f"Error: Permission denied reading {junit_file_path}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: Failed to parse JUnit XML file {junit_file_path}: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Extract statistics from testsuite element
    # JUnit XML format: <testsuite tests="N" failures="M" errors="E" skipped="S">
    testsuite = root.find('.//testsuite')
    if testsuite is None:
        # Try root element if it's the testsuite
        testsuite = root
    
    total_tests = testsuite.get('tests', '0')
    failures = int(testsuite.get('failures', '0'))
    errors = int(testsuite.get('errors', '0'))
    skipped = int(testsuite.get('skipped', '0'))
    
    # Calculate passed (total - failures - errors - skipped)
    total = int(total_tests)
    failed = failures + errors
    passed = total - failed - skipped
    
    statistics = {
        'total_tests': str(total),
        'passed': str(passed),
        'failed': str(failed),
        'timed_out': '0'  # JUnit XML doesn't distinguish timeouts, will be in failures
    }
    
    # Extract failed test cases
    failed_tests = []
    
    # Find all testcase elements with failure or error
    for testcase in root.findall('.//testcase'):
        failure = testcase.find('failure')
        error = testcase.find('error')
        
        if failure is not None or error is not None:
            test_name = testcase.get('name', 'unknown')
            classname = testcase.get('classname', '')
            
            # Combine classname and name for full test path
            if classname:
                full_name = f"{classname}::{test_name}"
            else:
                full_name = test_name
            
            # Check if it's a timeout (nextest may include timeout info in failure message)
            failure_message = ''
            if failure is not None:
                failure_message = failure.get('message', '')
            elif error is not None:
                failure_message = error.get('message', '')
            
            # Only mark as timeout and adjust counts if it's explicitly a timeout
            # Note: nextest should already count timeouts separately, but we detect them
            # from failure messages as a backup
            if 'timeout' in failure_message.lower() or 'timed out' in failure_message.lower():
                full_name = f"{full_name} (タイムアウト)"
                # Increment timeout count (failures already include timeouts in JUnit XML)
                statistics['timed_out'] = str(int(statistics['timed_out']) + 1)
            
            failed_tests.append(full_name)
    
    # Categorize failed tests
    categorized: Dict[str, List[str]] = {
        "Pipe Tests": [],
        "CLI Integration Tests": [],
        "Client Integration Tests": [],
        "Interactive Mode Tests": [],
        "Server Integration Tests": [],
        "その他": []
    }
    
    for test in failed_tests:
        category = categorize_test(test)
        categorized[category].append(test)
    
    return statistics, categorized


def format_categorized_output(categorized: Dict[str, List[str]]) -> str:
    """
    Format categorized test results as markdown.
    
    Args:
        categorized: Dict mapping category names to lists of failed tests
    
    Returns:
        Formatted markdown string
    """
    lines = []
    
    for category in sorted(categorized.keys()):
        tests = categorized[category]
        if len(tests) > 0:
            lines.append(f"\n#### {category} ({len(tests)}件)")
            for test in tests:
                lines.append(f"- {test}")
    
    return "\n".join(lines)


def main():
    """
    Main entry point for the script.
    """
    parser = argparse.ArgumentParser(
        description="Parse nextest JUnit XML output and extract test results."
    )
    
    parser.add_argument(
        "--junit-file",
        required=True,
        help="Path to the JUnit XML file generated by nextest"
    )
    
    parser.add_argument(
        "--output-format",
        choices=["stats", "categorized", "both"],
        default="both",
        help="Output format: stats (statistics only), categorized (failed tests only), or both"
    )
    
    args = parser.parse_args()
    
    statistics, categorized = parse_junit_xml(args.junit_file)
    
    if args.output_format in ["stats", "both"]:
        print(f"total_tests={statistics['total_tests']}")
        print(f"passed={statistics['passed']}")
        print(f"failed={statistics['failed']}")
        print(f"timed_out={statistics['timed_out']}")
    
    if args.output_format in ["categorized", "both"]:
        if args.output_format == "both":
            print("---")
        print(format_categorized_output(categorized))
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
